### DISCUSSION TITLE
Mobile optimisations

### DISCUSSION THREAD

**Discussion by Anagastes** [McShelby/hugo-theme-relearn#1094] [Ideas]
Hi!

I've been through a few hugo themes now and keep coming back to yours. It's just fucking simple and yet rich in features. I don't know how you do it, but keep it up.

I've now noticed that the theme could do with a few optimisations for mobile phones.

1. longer titles are broken unfavourably. I got round this with a custom CSS. But I think that would be nice in general. I simply minimised the size. But maybe you can solve this more elegantly with better wrapping or syllable recognition from the CSS.

Below is my CSS code (usable for all default themes).

```css
@import "theme-zen-dark.css";

@media only screen and (max-width: 47.999rem) {
  #R-body-inner > .flex-block-wrapper article.narrow h1 {
    font-size: 2.0rem;
  }
}
````

2. the ToC menu is not designed for fingers. Here is an example how the menu breaks the complete layout. Also there is no ‘X’ to close on the mobile phone. This makes it a bit unfavourable for users. :) 

Unfortunately I am not web-dev enough to do this myself.

![grafik](https://github.com/user-attachments/assets/b3dfb6b1-e64c-4a6d-a83b-47bcc2e1d58a)
