### DISCUSSION TITLE
How to hide entries from the menu

### DISCUSSION THREAD

**Discussion by cagix** [McShelby/hugo-theme-relearn#185] [Q&A] [answered]
The menu should not show hidden contents. However, if you access a hidden page via a link or directly, the corresponding menu entry appears. This is unexpected and (iirc) did not occur in the Hugo Learn theme.

Is this a bug or can it be configured so that hidden content never appears in the menu?

Here is an example: Opening https://mcshelby.github.io/hugo-theme-relearn/, "This could be yours" is hidden (as expected). If you then access https://mcshelby.github.io/hugo-theme-relearn/yours/, an entry appears in the menu (second screenshot).

<img width="845" alt="Screenshot 2022-02-17 at 10 36 33" src="https://user-images.githubusercontent.com/20356276/154448862-5105340a-b0cf-424b-8ff1-49bcbac2f877.png">

<img width="845" alt="Screenshot 2022-02-17 at 10 36 41" src="https://user-images.githubusercontent.com/20356276/154448914-2521f2f0-ac91-4f81-96e5-442dbfdaa49c.png">

**Comment by McShelby** [comment]
This is a feature and can not be configured. This behaviour differs from the Learn theme.

The rational behind is this:

Hidden means, the page is included in your site. If you don't want to include the page at all, you can set the page's frontmatter to `draft` (this is a Hugo feature).

Once a page is included in your site, it can always be accessed directly by typing the corresponding URL in the browser address bar regardless of its hidden state.

So far so good. Now the point is: If you are viewing a hidden page, you want to know where it is located in your site structure and therefore displays in the menu. Otherwise you wouldn't have a clue where it resides in your structure.

Keep in mind, that there are further config parameters to handle different aspects of hidden pages, like 

````toml
# Disable search in hidden pages, otherwise they will be shown in search box
disableSearchHiddenPages = false
# Disables hidden pages from showing up in the sitemap and on Google (et all), otherwise they may be indexed by search engines
disableSeoHiddenPages = false
# Disables hidden pages from showing up on the tags page although the tag term will be displayed even if all pages are hidden
disableTagHiddenPages = false
````

**Comment by cagix** [comment]
ah, i see. my aim was to address the hidden pages via the "More" section in the menu and to keep them completely out of the normal menu. 

example: in the normal menu i arrange the topics of my lecture (script, each lecture is a separate page). in the "More" part i arrange topics like syllabus, grading, ... these things should not appear as structure in the normal menu (even if you access them -- they are in "More"), so i set them to "hidden". 

i'll leave the issue open for now, in case you change your mind and want to make it configurable. feel free to close if you want to stay with the current interpretation.

**Comment by McShelby** [comment, marked as answer]
The hidden pages feature isn't made for your use case as your pages are obviously not meant to be hidden but only to be displayed in a different structure. That it worked for you in the Learn theme was - IMHO - a bug, and so I fixed it.

**But:** I may have a working solution for you:

1. If your pages aren't branch bundles, you could put them all to the root of your page (as eg. the `credits.html` of the `exampleSite`).
2. If you want to have any kind of bundles and even want to structure them in subdirectories, you can put some Hugo frontmatter options into your page (as eg. the `more/showcase/_index.en.md` of the `exampleSite`):

````toml
title = "Blub"
[_build]
  render = "always"
  list = "never"
  publishResources = true
````
See https://gohugo.io/content-management/build-options/
