### DISCUSSION TITLE
How to link to I18n'ed page?

### DISCUSSION THREAD

**Discussion by postb99** [McShelby/hugo-theme-relearn#688] [Q&A] [answered]
Hello, can you help me understand this documentation?
https://gohugo.io/content-management/multilingual/#localizing-permalinks

I have the following (shortened) configuration. My goal is to put direct shortcut to French or English home page in the menu when viewing the site in the other language, rather than using the language selector I may disable.

Default language is "fr" so "/en" url works, but when switching language to English, there is no correct url to go to French home page. According to the documentation, I tried to define url = "/home-fr" or "/home-en" in the _index.md (section index page).

EDIT: Found something interesting:
https://gohugo.io/content-management/urls/#url
But "/home-fr" leads to 404, not home page...

Thanks for helping,

    [Languages]
        [Languages.en]
            languageName = "English"
            contentDir = "content/en"
            title = "Poesieland"
            weight = 2
            [languages.en.params]
                landingPageName = "<i class='fas fa-home'></i> Home"
    
            [[Languages.en.menu.shortcuts]]
                name = "<i class='fas fa-fw fa-tags'></i> Tags"
                url = "/en/tags/"
                weight = 40
    
        [Languages.fr]
            languageName = "Français"
            contentDir = "content/fr"
            title = "Poésieland"
            weight = 1
            [languages.fr.params]
                landingPageName = "<i class='fas fa-home'></i> Accueil"

          [[Languages.fr.menu.shortcuts]]
              name = "<i class='fas fa-fw fa-tags'></i> Mots-clés"
              url = "/tags/"
              weight = 40
          [[Languages.fr.menu.shortcuts]]
              name = "<i class='fa fas fa-feather-pointed'></i> Poèmes écrits en anglais"
              url = "/en/original_texts/"
              weight = 55

**Comment by McShelby** [comment, marked as answer]
Quite tricky.

It worked for me in the exampleSite by adding

````toml
  [[languages.en.menu.shortcuts]]
    name = "<i class='fas fa-fw fa-skull-crossbones'></i> Piratish Docs"
    url = "../pir/"
    weight = 50

  [[languages.pir.menu.shortcuts]]
    name = "<i class='fas fa-fw fa-puzzle-piece'></i> Boring Docs"
    url = "../en/"
    weight = 50
````

Note to exchange `pageRef` with `url` in this case.
