### DISCUSSION TITLE
Is it possible to change the highlight style depending on theme variant?

### DISCUSSION THREAD

**Discussion by AndersBennedsgaard** [McShelby/hugo-theme-relearn#918] [Q&A] [answered]
I have tried to search through Hugo docs, `hugo-theme-relearn` docs, and Google, but I have not been able to find some easy to understand information about how to change the `markup.highlight.style` depending on the `params.themeVariant`. Is this not possible without a lot of Hugo magic and custom HTML/CSS?

Currently, we use these params and markup config:

```yaml
params:
  author.name: "<owner>"
  collapsibleMenu: true
  disableInlineCopyToClipBoard: true
  editURL: https://github.com/<org>/<repo>/edit/main/content/${FilePath}
  themeVariant:
    - identifier: zen-auto
      name: Auto
      auto:
        - zen-light
        - zen-dark
    - identifier: zen-dark
      name: Dark
    - identifier: zen-light
      name: Light

markup:
  highlight:
    style: tango
```

The `tango` highlight style renders some code blocks as unreadable white text when using the dark theme, as seen below:

![image](https://github.com/user-attachments/assets/5ea1417e-8c1a-40e2-bbbe-25311e5beca4)

With the light theme, the code block correctly shows `cosign generate-key-pair`
