### ISSUE TITLE
Highlight does not work

### ISSUE THREAD

**Issue by inrhor** [McShelby/hugo-theme-relearn#116]
I set it in config.toml
```toml
[markup]
  [markup.highlight]
    style = "base16-snazzy"
    guessSyntax = true
```
or
```toml
[markup]
  [markup.highlight]
    style = "base16-snazzy"
    guessSyntax = false
```

after
`
```YAML```
`

Showing white background
