### ISSUE TITLE
theme: generate correct links if theme served from subdirectory

### ISSUE THREAD

**Issue by McShelby** [McShelby/hugo-theme-relearn#120]
If your site is served from a subfolder, eg. `https://example.com/mysite/`, you have to set the following lines to your `config.toml`

````toml
baseURL = "https://example.com/mysite/"
canonifyURLs = true
````

Reference: matcornic/hugo-theme-learn#507
Reference: matcornic/hugo-theme-learn#468
Reference: matcornic/hugo-theme-learn#65
