### ISSUE TITLE
2.9.2 disableInlineCopyToClipBoard not effective

### ISSUE THREAD

**Issue by pbillerot** [McShelby/hugo-theme-relearn#164]
config.yaml
...
params:
  # Set this to true to disable copy-to-clipboard button for inline code.
  disableInlineCopyToClipBoard: true

![image](https://user-images.githubusercontent.com/2213723/147359747-040aacbf-ead4-4595-923e-f039b100256e.png)

**Comment by McShelby** [comment]
Works for me and the exampleSite. What's with your second snippet?

**Comment by pbillerot** [comment]
It's the result of this code
```
    ```yaml
    # Champ en lecture seule.
    read-only: true
    ```
```

**Comment by McShelby** [comment]
As the config options reads: disable**Inline**CopyToClipBoard, which effectifly means this style:

![grafik](https://user-images.githubusercontent.com/11670870/147362862-4e7bbcb5-2d7d-4c54-b73c-2deca5ace331.png)

**Comment by pbillerot** [comment]
My Hugo version
`Hugo Static Site Generator v0.80.0/extended linux/amd64 BuildDate: 2021-07-18T09:31:51Z (debian 0.80.0-6+b5)`

With the exampleSite : 
```
>hugo serve
Error: add site dependencies: load resources: loading templates: "/home/billerot/Dev/relearn-test/layouts/shortcodes/piratify.html:3:1": parse failed: template: shortcodes/piratify.html:3: unclosed action
```
after the corrections by pasting all in one line, it's ok

in config.toml I added the line `disableLandingPageButton = true`
```toml
[params]
  editURL = "https://github.com/McShelby/hugo-theme-relearn/edit/main/exampleSite/content/"
  description = "Documentation for Hugo Relearn Theme"
  author = "Sören Weber"
  showVisitedLinks = true
  disableBreadcrumb = false
  disableNextPrev = false
  disableLandingPageButton = true
  disableMermaid = false
  titleSeparator = "::"
  themeVariant = "relearn"
  disableSeoHiddenPages = true
  disableInlineCopyToClipBoard = true
```
and the icon to paste the code is always displayed

![image](https://user-images.githubusercontent.com/2213723/147364529-38abd817-140c-485f-839d-b9c7d652b826.png)
