### ISSUE TITLE
White space between Menu window and page content

### ISSUE THREAD

**Issue by kadavil** [McShelby/hugo-theme-relearn#247]
I was wondering if there is a way to reduce the white space between the Menu window and the Page content. On a full screen, the white space seems too much compared to how it behaved in the learn theme.  I am trying to port our doc site from learn theme to relearn theme and noticing these subtle spacing issues. 

Is there a setting to define the spacing? 

**Relearn theme**
<img width="1582" alt="image" src="https://user-images.githubusercontent.com/4380702/169567011-ca0bae9f-a9a3-4d24-91a3-dbd015f4a118.png">

**Learn theme**
<img width="1662" alt="image" src="https://user-images.githubusercontent.com/4380702/169566865-e285ed45-67dd-439d-9d86-0bc9d9d64001.png">

Thanks

**Comment by McShelby** [comment]
At a certain resolution (read: screen width), the theme locks the width of its content to avoid getting text lines to long. https://baymard.com/blog/line-length-readability

Nevertheless you can change this by defining your own CSS in `custom-header.html` 

Rule from `theme.css`:

````css
/* we limit width if we have large screens */
@media screen and ( min-width: 1300px ){ /* #sidebar/width + ./max-width */
    #body .flex-block-wrapper {
        margin-left: auto;
        margin-right: auto;
        max-width: 1000px;
    }
}
````

Please remember, that this is not a documented feature and therefore overwriting the rule may break in any newer version of the theme.
