### ISSUE TITLE
Add references directly to main menu?

### ISSUE THREAD

**Issue by RoarkGit** [McShelby/hugo-theme-relearn#652]
I am trying to add some external (and internal) URLs to the main menu, but it doesn't seem to work properly. It works fine in other themes, so I'm wondering if I'm doing something wrong here. Note: `menu.shortcuts` works fine, it's `menu.main` that does not.

```
menu:
  main:
    - name: Google
      url: https://www.google.com
      weight: 100
```

I've also been trying this with some internal URLs and it still doesn't seem to show up at all.
