### ISSUE TITLE
highlight: fix codefence syntax in Hugo >= 0.121.0

### ISSUE THREAD

**Issue by ehbauer** [McShelby/hugo-theme-relearn#749]
With the latest version of the Relearn theme I ran into a strange problem that only happens in the Gitlab build of a Hugo project that uses the theme. The Gitlab setup is the easiest from the docs:

```
image: registry.gitlab.com/pages/hugo/hugo_extended:latest

variables:
  GIT_SUBMODULE_STRATEGY: recursive

pages:
  script:
    - hugo
  artifacts:
    paths:
      - public
  rules:
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH
```

In one template I have some code snippets that specify a starting line number

```
```yaml {linenos=inline,linenostart=50}
# FINAL BUILD
FROM ubuntu-nginx-php:3.0.2-fpm8.2 AS prod
...
```

When building this fails with an error

> Error: error building site: "/builds/nyyoy3xx/0/xxx/content/dev/boilerplate/docker/_index.md:149:1": execute of template failed: template: _default/_markup/render-codeblock.html:1:4: executing "_default/_markup/render-codeblock.html" at <partial "shortcodes/highlight.html" (dict "page" .Page "attributes" .Attributes "content" .Inner "options" .Options "type" .Type)>: error calling partial: "/builds/nyyoy3xx/0/xxxx/themes/relearn/layouts/partials/shortcodes/highlight.html:83:15": execute of template failed: template: partials/shortcodes/highlight.html:83:15: executing "partials/shortcodes/highlight.html" at <highlight $content $type $params>: error calling highlight: invalid Highlight option: linenostart

I couldn't really understand what the problem was and had to remove the linenostart specification for this to work. It is still mentioned in the docs and I don't see a relevant change in the highligh shortcode partial that would create the issue.
