### ISSUE TITLE
theme: switch font

### ISSUE THREAD

**Issue by McShelby** [McShelby/hugo-theme-relearn#83]
Currently the used fonts have difficulties to display unicode characters for chinese and other languages.

Additionally reconsider support font formats. Probably woff and woff2 are enough.

Switching fonts may impact a site's look&feel, so better hide the new font behind a config parameter.

**Comment by The-going** [comment]
I think you closed the discussion prematurely.
The font [Work Sans](https://fonts-online.ru/fonts/work-sans) is a variable font and belongs to the categories grotesque, decorative, for titles, for texts. The headset contains 2 files. Supports  **63 languages**. It has a SIL OFL 1.1 license. It can be used in commercial and non-commercial activities. The development of the Work Sans font was carried out by Wei Huang.

Today I use Open Sans as the main font.
The [Open Sans](https://fonts-online.ru/fonts/open-sans) font is a variable font and belongs to the categories grotesque, decorative. The headset contains 2 files. Supports **73 languages**. It belongs to the Open Sans font family. It has an Apache 2.0 license. It can be used in commercial and non-commercial activities. The Open Sans font was developed by Steve Matteson.

And from my point of view, it is more preferable for a multilingual site. But there are some details.
I had to make a separate css file for the fonts in order for the design of the source site to be as close to multilingual as possible.

#### font-mix.css
```css
body #chapter h1 {
    font-size: 3.5rem;
}

#chapter h2 {
    font-family: "Open Sans", "Work Sans", "Helvetica", "Tahoma", "Geneva", "Arial", sans-serif;
    font-weight: 300;
    text-align: center;
}

body {
    font-family: "Open Sans", "Source Sans Pro", "Work Sans", "Helvetica", "Tahoma", "Geneva", "Arial", sans-serif;
    #font-weight: 300;
    #line-height: 1.6;
	letter-spacing: 0.7px;
	text-rendering: optimizeLegibility;
    font-size: 16px !important;
	color: var(--MAIN-TEXT-color) !important;
}

h2, h3, h4, h5, h6 {
    color: var(--MAIN-TITLES-TEXT-color) !important;
	font-family: "Open Sans Semibold", "Work Sans", "Helvetica", "FreeSans", "Open Sans", sans-serif;
	#text-rendering: optimizeLegibility;
	color: #5e5e5e;
	letter-spacing: 0.8px;
	#font-size: 28.0px !important;
}

h1 {
	font-family:  "Cantarell Light", "Open Sans Light", "Helvetica", "Tahoma", "Geneva", "Arial", sans-serif;
	#font-weight: Thin; # Thin or Light
	#line-height: 0.8;
	text-align: center;
    text-rendering: optimizeLegibility;
    color: var(--MAIN-TEXT-color) !important;
    letter-spacing: -1px;
	font-size: 48px !important;
}

/* Redefines headers style for font-family: "Open Sans Semibold" */

h1 a, h2 a, h3 a, h4 a, h5 a, h6 a {
  font-weight: inherit;
}

#body h2 {
  font-size: 2.4rem;
  #font-weight: 400;
  margin-top: 2rem;
}

#body h3 {
  font-size: 2.1rem;
  #font-weight: 400;
  margin-top: 2rem;
}

#body h4 {
  font-size: 1.8rem;
  #font-weight: 200;
  margin-top: 2rem;
}

#body h5 {
  font-size: 1.5rem;
  #font-weight: 200;
  margin-top: 2rem;
}

#body h6 {
  font-size: 1.2rem;
  #font-weight: 200;
  margin-top: 2rem;
}

code, kbd, pre, samp {
    font-family: "Hack", "PT Mono", "Source Code Pro", "Consolas", menlo, monospace;
    font-size: 110%;
    vertical-align: baseline;
}

code {
	font-family: "Hack", "PT Mono", "Source Code Pro";
	#font-size: 110% !important;
	line-height: 1.3;
    border-radius: 2px;
    white-space: nowrap;
    color: #5e5e5e;
    background: #ffffff;
    border: 0px;
    padding: 0px 3px;
}

div.proto {
    font-family: "Font Awesome 5 Free";
    font-weight: 500;
    font-family: "Hack", "Source Code Pro", "Consolas", menlo, monospace;
    font-size: 115%;
}

```

It probably makes sense to reopen this issue, and other people will be able to say their opinion here.
