### ISSUE TITLE
h4 heading has a larger font size than h3

### ISSUE THREAD

**Issue by Yosh31207** [McShelby/hugo-theme-relearn#833]
Is this a intended style?

static/css/theme.css

```css
h3, .article-subheading {
    font-size: 1.8rem;
    font-weight: 500;
}

h4 {
    font-size: 1.85rem;
    font-weight: 300;
}
```
