### ISSUE TITLE
Cannot load custom CSS from anywhere

### ISSUE THREAD

**Issue by dei-layborer** [McShelby/hugo-theme-relearn#945]
I've tried to create a new color scheme, but it's not working properly (or at all).

I made copies of ``theme-relearn-dark.css`` and ``theme-relearn-bright.css`` in ``/themes/hugo-theme-relearn/assets/css/``, and saved them to /[site root]/assets/css`` as ``theme-custom-dark.css`` and ``theme-custom-bright.css``.  I then added this to ``hugo.toml``:

```toml
[params]

  [[params.themeVariant]]
    auto = ['custom-bright', 'custom-dark']
    identifier = 'custom-auto'
    name = 'OS Preference'

  [[params.themeVariant]]
    identifier = 'custom-bright'
    name = 'Light Theme'

  [[params.themeVariant]]
    identifier = 'custom-dark'
    name = 'Dark Theme'
```

The light/dark picker or whatever in the bottom-left of the page sees both of these, and changing between light and dark mode works as expected.  However, actually changing the .css file (such as a variable) does not appear in the site.  According to the inspector in Firefox, it *is* loading ``theme-custom-dark.css``, but any changes I make somehow aren't reflected in what's rendered.

I tried moving those files to ``/themes/hugo-theme-relearn/assets/css`` just in case the documentation was wrong, but the results were the same.

Meanwhile, following #868, I added the following to ``layouts/partials/custom-header.html``:

```
<link rel="stylesheet" href="/css/theme-overrides.css">
```

The file referenced is in ``[site root]/static/css/``.  However, it's not being loaded at all as far as I can tell (and none of the rules in there are applied to the page).

I'm using the newest version of the theme (downloaded it today), and am running hugo version ``0.131.0+extended``.  At this point I don't know what I'm supposed to do.  Any ideas?
