### ISSUE TITLE
Custom google fonts or @font-face in theme files

### ISSUE THREAD

**Issue by Ynn** [McShelby/hugo-theme-relearn#994]
Hi,

Before version **7.2**, I could easily import and use custom fonts like this:

```css
@import "theme-blue.css";

@import url('https://fonts.googleapis.com/css2?family=IBM+Plex+Sans:ital,wght@0,100;0,200;0,300;0,400;0,500;0,600;0,700;1,100;1,200;1,300;1,400;1,500;1,600;1,700&display=swap');

:root {    
    --MAIN-font: "IBM Plex Sans", "Atkinson Hyperlegible";
    --MAIN-TITLES-TEXT-font: "IBM Plex Sans", "Work Sans", "Helvetica", "Tahoma", "Geneva", "Arial", sans-serif;
    --MAIN-TITLES-H1-font: var(--INTERNAL-MAIN-TITLES-TEXT-font);
    --MAIN-MENU-TEXT-font: var(--MAIN-TITLES-TEXT-font);
    
    --MAIN-TEXT-color: rgba(50, 50, 50, 1); /* Color of text by default */
    --MAIN-TITLES-TEXT-color: rgba(94, 94, 94, 1); /* Color of titles h2-h3-h4-h5-h6 */
    --MAIN-TITLES-H1-color: rgba(34, 34, 34, 1); /* Text color of h1 titles */
    --MAIN-LINK-color: rgba(28, 144, 243, 1); /* Color of links */
    --MAIN-LINK-HOVER-color: rgba(22, 122, 208, 1); /* Color of hovered links */
    --MAIN-BG-color: rgba(255, 255, 255, 1); /* Background color */
}

#R-sidebar {
    font-family: var(--MAIN-MENU-TEXT-font);
}

#R-body-inner {
    font-size: 1.2rem;
    line-height: 1.5;
    word-spacing: 0.16em;
}

@media screen and (min-width: 1400px) {
    #R-body .flex-block-wrapper {
        width: calc(90rem - var(--INTERNAL-MENU-WIDTH-L) - 2 * 3.25rem);
        max-width: calc(90rem - var(--INTERNAL-MENU-WIDTH-L) - 2 * 3.25rem);
    }
}

img.diagram {
    height: auto;
    width: 100%;
}
```

This worked perfectly until version **7.2**. Same  when loading fonts with @font-face in theme-mytheme.css

---

### The Problem:
Since upgrading to **7.2**, the custom fonts are no longer loaded. While the CSS variables and rules are correctly applied (e.g., using system fonts like Arial works fine), the browser fails to load fonts imported from external sources (like Google Fonts) or locally hosted fonts.

I suspect this issue might be related to the changes introduced in #757 but I’m not sure.

---

### Question:
What is the proper way to load custom fonts for themes in **7.2**? Is there a specific step or updated method required to ensure that fonts are loaded and applied correctly per theme?

Any guidance would be much appreciated. Thanks!
